/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hungv
 */
public class frmThongTinCanBo extends javax.swing.JFrame {

    DefaultTableModel dtmHocTap=new DefaultTableModel();
    DefaultTableModel dtmCongTac=new DefaultTableModel();
    DefaultTableModel dtmChucVu=new DefaultTableModel();
    DefaultTableModel dtmChucDanh=new DefaultTableModel();
    DefaultTableModel dtmLuong=new DefaultTableModel();
    DefaultTableModel dtmGiaDinh=new DefaultTableModel();
    /**
     * Creates new form ThongTinChiTietCanBoView
     */
    public frmThongTinCanBo() {
        initComponents();
        creadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTab = new javax.swing.JTabbedPane();
        pnThongTinChung = new javax.swing.JPanel();
        lblMaCanBo = new javax.swing.JLabel();
        txtMaCanBo = new javax.swing.JTextField();
        lblNganh = new javax.swing.JLabel();
        txtNganh = new javax.swing.JTextField();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        lblGioiTinh = new javax.swing.JLabel();
        lblChucDanh = new javax.swing.JLabel();
        txtChucDanh = new javax.swing.JTextField();
        lblChucVu = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JTextField();
        lblMaSoThue = new javax.swing.JLabel();
        txtMaSoThue = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btgNam = new javax.swing.JRadioButton();
        btgNu = new javax.swing.JRadioButton();
        pnGiaDinh = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGiaDinh = new javax.swing.JTable(dtmGiaDinh);
        btnXoaGiaDinh = new javax.swing.JButton();
        btnSuaGiaDinh = new javax.swing.JButton();
        btnThemGiaDinh = new javax.swing.JButton();
        pnQuaTrinhHocTap = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQuaTrinhHocTap = new javax.swing.JTable(dtmHocTap);
        btnXoaHocTap = new javax.swing.JButton();
        btnSuaHocTap = new javax.swing.JButton();
        btnThemHocTap = new javax.swing.JButton();
        pnQuaTrinhCongTac = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblQuaTrinhCongTac = new javax.swing.JTable(dtmCongTac);
        btnXoaCongTac = new javax.swing.JButton();
        btnSuaCongTac = new javax.swing.JButton();
        btnThemCongTac = new javax.swing.JButton();
        pnQuaTrinhChucVu = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblQuaTrinhChucVu = new javax.swing.JTable(dtmChucVu);
        btnXoaChucVu = new javax.swing.JButton();
        btnSuaChucVu = new javax.swing.JButton();
        btnThemChucVu = new javax.swing.JButton();
        pnQuaTrinhChucDanh = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblQuaTrinhChucDanh = new javax.swing.JTable(dtmChucDanh);
        btnXoaChucDanh = new javax.swing.JButton();
        btnSuaChucDanh = new javax.swing.JButton();
        btnThemChucDanh = new javax.swing.JButton();
        pnQuaTrinhLuong = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblQuaTrinhLuong = new javax.swing.JTable(dtmLuong);
        btnXoaLuong = new javax.swing.JButton();
        btnSuaLuong = new javax.swing.JButton();
        btnThemLuong = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblKhenThuong1 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        txtMaSoKyLuat = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtSoTienPhat = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtLyDoKyLuat = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblKhenThuong = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtMaSoKhenThuong = new javax.swing.JTextField();
        txtSoTienThuong = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtLyDoThuong = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtHeSoBac = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPhuCapChucVu = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPhuCapNganh = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtNamThamNien = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtHeSoThamNien = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtHeSoCong = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtBaoHiemXaHoi = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtBaoHiemYTe = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtBaoHiemThatNghiep = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtLuongToiThieu = new javax.swing.JTextField();
        txtLuongDuocNhan = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtMaSoCanBo2 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMaCanBo.setText("MÃ CÁN BỘ");

        lblNganh.setText("NGẠCH");

        lblHoTen.setText("HỌ TÊN");

        lblNgaySinh.setText("NGÀY SINH");

        lblGioiTinh.setText("GIỚI TÍNH");

        lblChucDanh.setText("CHỨC DANH");

        lblChucVu.setText("CHỨC VỤ");

        lblMaSoThue.setText("MÃ SỐ THUẾ");

        jButton2.setText("Cập nhật");

        jLabel1.setText("SỐ TÀI KHOẢN");

        jLabel2.setText("EMAIL");

        jLabel3.setText("ĐẢNG VIÊN");

        jLabel4.setText("CÔNG ĐOÀN VIÊN");

        jLabel5.setText("MÃ CHI BỘ");

        jLabel6.setText("ĐỊA CHỈ");

        jLabel7.setText("SỐ ĐIỆN THOẠI");

        jLabel8.setText("ĐOÀN VIÊN");

        jLabel9.setText("MÃ TỔ CÔNG ĐOÀN");

        jLabel10.setText("THÀNH TÍCH");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane7.setViewportView(jTextArea1);

        btgNam.setText("Nam");
        btgNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgNamActionPerformed(evt);
            }
        });

        btgNu.setText("Nữ");

        javax.swing.GroupLayout pnThongTinChungLayout = new javax.swing.GroupLayout(pnThongTinChung);
        pnThongTinChung.setLayout(pnThongTinChungLayout);
        pnThongTinChungLayout.setHorizontalGroup(
            pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinChungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinChungLayout.createSequentialGroup()
                        .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnThongTinChungLayout.createSequentialGroup()
                                .addComponent(lblMaCanBo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(txtMaCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnThongTinChungLayout.createSequentialGroup()
                                .addComponent(lblHoTen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnThongTinChungLayout.createSequentialGroup()
                                .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblChucVu)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(lblGioiTinh))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinChungLayout.createSequentialGroup()
                                        .addComponent(btgNam)
                                        .addGap(18, 18, 18)
                                        .addComponent(btgNu)
                                        .addGap(26, 26, 26))
                                    .addComponent(txtChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField5))))
                        .addGap(96, 96, 96))
                    .addGroup(pnThongTinChungLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(430, 430, 430)))
                .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinChungLayout.createSequentialGroup()
                        .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnThongTinChungLayout.createSequentialGroup()
                                    .addComponent(lblMaSoThue)
                                    .addGap(75, 75, 75)
                                    .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                        .addComponent(txtMaSoThue)
                                        .addComponent(jTextField6)
                                        .addComponent(jTextField7)
                                        .addComponent(jTextField8)
                                        .addComponent(jTextField9)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinChungLayout.createSequentialGroup()
                                    .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNganh)
                                        .addComponent(lblNgaySinh)
                                        .addComponent(lblChucDanh))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtChucDanh, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                        .addComponent(txtNganh)
                                        .addComponent(txtNgaySinh)))
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel2))
                        .addContainerGap(93, Short.MAX_VALUE))
                    .addGroup(pnThongTinChungLayout.createSequentialGroup()
                        .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnThongTinChungLayout.setVerticalGroup(
            pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinChungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaCanBo)
                    .addComponent(txtMaCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNganh)
                    .addComponent(txtNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoTen)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgaySinh)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioiTinh)
                    .addComponent(lblChucDanh)
                    .addComponent(txtChucDanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btgNam)
                    .addComponent(btgNu))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChucVu)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaSoThue)
                    .addComponent(txtMaSoThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinChungLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnThongTinChungLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 53, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pnTab.addTab("THÔNG TIN CHUNG", pnThongTinChung);

        jScrollPane1.setViewportView(tblGiaDinh);

        btnXoaGiaDinh.setText("XÓA");

        btnSuaGiaDinh.setText("SỬA");

        btnThemGiaDinh.setText("THÊM");

        javax.swing.GroupLayout pnGiaDinhLayout = new javax.swing.GroupLayout(pnGiaDinh);
        pnGiaDinh.setLayout(pnGiaDinhLayout);
        pnGiaDinhLayout.setHorizontalGroup(
            pnGiaDinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnGiaDinhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemGiaDinh)
                .addGap(46, 46, 46)
                .addComponent(btnSuaGiaDinh)
                .addGap(41, 41, 41)
                .addComponent(btnXoaGiaDinh)
                .addContainerGap())
        );
        pnGiaDinhLayout.setVerticalGroup(
            pnGiaDinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGiaDinhLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnGiaDinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaGiaDinh)
                    .addComponent(btnSuaGiaDinh)
                    .addComponent(btnThemGiaDinh))
                .addContainerGap())
        );

        pnTab.addTab("GIA ĐÌNH", pnGiaDinh);

        jScrollPane2.setViewportView(tblQuaTrinhHocTap);

        btnXoaHocTap.setText("XÓA");

        btnSuaHocTap.setText("SỬA");

        btnThemHocTap.setText("THÊM");

        javax.swing.GroupLayout pnQuaTrinhHocTapLayout = new javax.swing.GroupLayout(pnQuaTrinhHocTap);
        pnQuaTrinhHocTap.setLayout(pnQuaTrinhHocTapLayout);
        pnQuaTrinhHocTapLayout.setHorizontalGroup(
            pnQuaTrinhHocTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnQuaTrinhHocTapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemHocTap)
                .addGap(44, 44, 44)
                .addComponent(btnSuaHocTap)
                .addGap(42, 42, 42)
                .addComponent(btnXoaHocTap)
                .addContainerGap())
        );
        pnQuaTrinhHocTapLayout.setVerticalGroup(
            pnQuaTrinhHocTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuaTrinhHocTapLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnQuaTrinhHocTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaHocTap)
                    .addComponent(btnSuaHocTap)
                    .addComponent(btnThemHocTap))
                .addContainerGap())
        );

        pnTab.addTab("QUÁ TRÌNH HỌC TẬP", pnQuaTrinhHocTap);

        jScrollPane3.setViewportView(tblQuaTrinhCongTac);

        btnXoaCongTac.setText("XÓA");

        btnSuaCongTac.setText("SỬA");

        btnThemCongTac.setText("THÊM");

        javax.swing.GroupLayout pnQuaTrinhCongTacLayout = new javax.swing.GroupLayout(pnQuaTrinhCongTac);
        pnQuaTrinhCongTac.setLayout(pnQuaTrinhCongTacLayout);
        pnQuaTrinhCongTacLayout.setHorizontalGroup(
            pnQuaTrinhCongTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnQuaTrinhCongTacLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemCongTac)
                .addGap(49, 49, 49)
                .addComponent(btnSuaCongTac)
                .addGap(43, 43, 43)
                .addComponent(btnXoaCongTac)
                .addContainerGap())
        );
        pnQuaTrinhCongTacLayout.setVerticalGroup(
            pnQuaTrinhCongTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuaTrinhCongTacLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnQuaTrinhCongTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaCongTac)
                    .addComponent(btnSuaCongTac)
                    .addComponent(btnThemCongTac))
                .addContainerGap())
        );

        pnTab.addTab("QUÁ TRÌNH CÔNG TÁC", pnQuaTrinhCongTac);

        jScrollPane4.setViewportView(tblQuaTrinhChucVu);

        btnXoaChucVu.setText("XÓA");

        btnSuaChucVu.setText("SỬA");

        btnThemChucVu.setText("THÊM");

        javax.swing.GroupLayout pnQuaTrinhChucVuLayout = new javax.swing.GroupLayout(pnQuaTrinhChucVu);
        pnQuaTrinhChucVu.setLayout(pnQuaTrinhChucVuLayout);
        pnQuaTrinhChucVuLayout.setHorizontalGroup(
            pnQuaTrinhChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnQuaTrinhChucVuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemChucVu)
                .addGap(38, 38, 38)
                .addComponent(btnSuaChucVu)
                .addGap(39, 39, 39)
                .addComponent(btnXoaChucVu)
                .addContainerGap())
        );
        pnQuaTrinhChucVuLayout.setVerticalGroup(
            pnQuaTrinhChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuaTrinhChucVuLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnQuaTrinhChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaChucVu)
                    .addComponent(btnSuaChucVu)
                    .addComponent(btnThemChucVu))
                .addContainerGap())
        );

        pnTab.addTab("QUÁ TRÌNH CHỨC VỤ", pnQuaTrinhChucVu);

        jScrollPane5.setViewportView(tblQuaTrinhChucDanh);

        btnXoaChucDanh.setText("XÓA");

        btnSuaChucDanh.setText("SỬA");

        btnThemChucDanh.setText("THÊM");

        javax.swing.GroupLayout pnQuaTrinhChucDanhLayout = new javax.swing.GroupLayout(pnQuaTrinhChucDanh);
        pnQuaTrinhChucDanh.setLayout(pnQuaTrinhChucDanhLayout);
        pnQuaTrinhChucDanhLayout.setHorizontalGroup(
            pnQuaTrinhChucDanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnQuaTrinhChucDanhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemChucDanh)
                .addGap(47, 47, 47)
                .addComponent(btnSuaChucDanh)
                .addGap(46, 46, 46)
                .addComponent(btnXoaChucDanh)
                .addContainerGap())
        );
        pnQuaTrinhChucDanhLayout.setVerticalGroup(
            pnQuaTrinhChucDanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuaTrinhChucDanhLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnQuaTrinhChucDanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaChucDanh)
                    .addComponent(btnSuaChucDanh)
                    .addComponent(btnThemChucDanh))
                .addContainerGap())
        );

        pnTab.addTab("QUÁ TRÌNH CHỨC DANH", pnQuaTrinhChucDanh);

        jScrollPane6.setViewportView(tblQuaTrinhLuong);

        btnXoaLuong.setText("XÓA");

        btnSuaLuong.setText("SỬA");

        btnThemLuong.setText("THÊM");

        javax.swing.GroupLayout pnQuaTrinhLuongLayout = new javax.swing.GroupLayout(pnQuaTrinhLuong);
        pnQuaTrinhLuong.setLayout(pnQuaTrinhLuongLayout);
        pnQuaTrinhLuongLayout.setHorizontalGroup(
            pnQuaTrinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnQuaTrinhLuongLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemLuong)
                .addGap(44, 44, 44)
                .addComponent(btnSuaLuong)
                .addGap(35, 35, 35)
                .addComponent(btnXoaLuong)
                .addContainerGap())
        );
        pnQuaTrinhLuongLayout.setVerticalGroup(
            pnQuaTrinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuaTrinhLuongLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnQuaTrinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaLuong)
                    .addComponent(btnSuaLuong)
                    .addComponent(btnThemLuong))
                .addContainerGap())
        );

        pnTab.addTab("QUÁ TRÌNH LƯƠNG", pnQuaTrinhLuong);

        tblKhenThuong1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(tblKhenThuong1);

        jLabel26.setText("MÃ SỐ");

        jLabel27.setText("NGÀY KỶ LUẬT");

        jLabel28.setText("SỐ TIỀN PHẠT");

        jLabel29.setText("LÝ DO");

        txtLyDoKyLuat.setColumns(20);
        txtLyDoKyLuat.setRows(5);
        jScrollPane11.setViewportView(txtLyDoKyLuat);

        jButton9.setText("Xóa");

        jButton10.setText("Sửa");

        jButton11.setText("Thêm");

        jDateChooser2.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane10)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaSoKyLuat)
                            .addComponent(txtSoTienPhat, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(195, 195, 195)
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtMaSoKyLuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtSoTienPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9))
                    .addComponent(jScrollPane11))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pnTab.addTab("KỶ LUẬT", jPanel2);

        tblKhenThuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tblKhenThuong);

        jLabel11.setText("MÃ SỐ");

        jLabel12.setText("NGÀY KHEN THƯỞNG");

        jLabel13.setText("SỐ TIỀN THƯỞNG");

        jLabel15.setText("LÝ DO");

        txtLyDoThuong.setColumns(20);
        txtLyDoThuong.setRows(5);
        jScrollPane9.setViewportView(txtLyDoThuong);

        jButton3.setText("Thêm");

        jButton4.setText("Sửa");

        jButton5.setText("Xóa");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane8)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaSoKhenThuong)
                            .addComponent(txtSoTienThuong)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                        .addGap(195, 195, 195)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtMaSoKhenThuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtSoTienThuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane9))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pnTab.addTab("KHEN THƯỞNG", jPanel3);

        jLabel16.setText("HỆ SỐ BẬC");

        jLabel17.setText("PHỤC CẤP CHỨC VỤ");

        jLabel18.setText("PHỤ CẤP NGÀNH");

        jLabel19.setText("NĂM THÂM NIÊN");

        jLabel20.setText("HỆ SỐ THÂM NIÊN");

        jLabel21.setText("HỆ SỐ CỘNG");

        jLabel22.setText("BẢO HIỂM XÃ HỘI");

        jLabel23.setText("BẢO HIỂM Y TẾ");

        jLabel24.setText("BẢO HIỂM THẤT NGHIỆP");

        jLabel25.setText("LƯƠNG TỐI THIỂU");

        txtLuongDuocNhan.setText("LƯƠNG ĐƯỢC NHẬN");

        jButton6.setText("SỬA");

        jButton7.setText("XÓA");

        jButton8.setText("ĐÓNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHeSoBac, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHeSoCong, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHeSoThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhuCapNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhuCapChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBaoHiemYTe, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addGap(50, 50, 50)
                                    .addComponent(txtBaoHiemXaHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLuongToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBaoHiemThatNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31))
                    .addComponent(txtLuongDuocNhan))
                .addGap(189, 189, 189))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(34, 34, 34)
                .addComponent(jButton7)
                .addGap(28, 28, 28)
                .addComponent(jButton8)
                .addGap(21, 21, 21))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton6, jButton7});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtHeSoBac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtBaoHiemXaHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtPhuCapChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtBaoHiemYTe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtPhuCapNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(txtBaoHiemThatNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtNamThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txtLuongToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtHeSoThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLuongDuocNhan)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtHeSoCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(21, 21, 21))
        );

        pnTab.addTab("LƯƠNG", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cán bộ"));

        jLabel14.setText("Mã số cán bộ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(72, 72, 72)
                .addComponent(txtMaSoCanBo2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSoCanBo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)))
        );

        jButton12.setText("Đóng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTab)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(pnTab, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btgNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btgNamActionPerformed

    private void creadTable() {
        dtmGiaDinh.addColumn("HỌ TÊN");
        dtmGiaDinh.addColumn("NĂM SINH");
        dtmGiaDinh.addColumn("THÀNH TÍCH CON");
        
        dtmHocTap.addColumn("THỜI GIAN HỌC TẬP");
        dtmHocTap.addColumn("NỘI DUNG HỌC TẬP");
        dtmHocTap.addColumn("TRƯỜNG");
        dtmHocTap.addColumn("BẰNG");
        
        dtmCongTac.addColumn("THỜI GIAN CÔNG TÁC");
        dtmCongTac.addColumn("CÔNG VIỆC");
        dtmCongTac.addColumn("CƠ QUAN");
        
        dtmChucVu.addColumn("NGÀY HIỆU LỰC");
        dtmChucVu.addColumn("CHỨC VỤ");
        dtmChucVu.addColumn("NHIỆM KỲ");
        dtmChucVu.addColumn("HẾT HIỆU LỰC");
        
        dtmChucDanh.addColumn("NGÀY HIỆU LỰC");
        dtmChucDanh.addColumn("CHỨC DANH");
        dtmChucDanh.addColumn("HẾT HIỆU LỰC");
        
        dtmLuong.addColumn("HỆ SỐ LƯƠNG");
        dtmLuong.addColumn("BHXH");
        dtmLuong.addColumn("BHYT");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmThongTinCanBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmThongTinCanBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmThongTinCanBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmThongTinCanBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmThongTinCanBo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btgNam;
    private javax.swing.JRadioButton btgNu;
    private javax.swing.JButton btnSuaChucDanh;
    private javax.swing.JButton btnSuaChucVu;
    private javax.swing.JButton btnSuaCongTac;
    private javax.swing.JButton btnSuaGiaDinh;
    private javax.swing.JButton btnSuaHocTap;
    private javax.swing.JButton btnSuaLuong;
    private javax.swing.JButton btnThemChucDanh;
    private javax.swing.JButton btnThemChucVu;
    private javax.swing.JButton btnThemCongTac;
    private javax.swing.JButton btnThemGiaDinh;
    private javax.swing.JButton btnThemHocTap;
    private javax.swing.JButton btnThemLuong;
    private javax.swing.JButton btnXoaChucDanh;
    private javax.swing.JButton btnXoaChucVu;
    private javax.swing.JButton btnXoaCongTac;
    private javax.swing.JButton btnXoaGiaDinh;
    private javax.swing.JButton btnXoaHocTap;
    private javax.swing.JButton btnXoaLuong;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblChucDanh;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMaCanBo;
    private javax.swing.JLabel lblMaSoThue;
    private javax.swing.JLabel lblNganh;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JPanel pnGiaDinh;
    private javax.swing.JPanel pnQuaTrinhChucDanh;
    private javax.swing.JPanel pnQuaTrinhChucVu;
    private javax.swing.JPanel pnQuaTrinhCongTac;
    private javax.swing.JPanel pnQuaTrinhHocTap;
    private javax.swing.JPanel pnQuaTrinhLuong;
    private javax.swing.JTabbedPane pnTab;
    private javax.swing.JPanel pnThongTinChung;
    private javax.swing.JTable tblGiaDinh;
    private javax.swing.JTable tblKhenThuong;
    private javax.swing.JTable tblKhenThuong1;
    private javax.swing.JTable tblQuaTrinhChucDanh;
    private javax.swing.JTable tblQuaTrinhChucVu;
    private javax.swing.JTable tblQuaTrinhCongTac;
    private javax.swing.JTable tblQuaTrinhHocTap;
    private javax.swing.JTable tblQuaTrinhLuong;
    private javax.swing.JTextField txtBaoHiemThatNghiep;
    private javax.swing.JTextField txtBaoHiemXaHoi;
    private javax.swing.JTextField txtBaoHiemYTe;
    private javax.swing.JTextField txtChucDanh;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtHeSoBac;
    private javax.swing.JTextField txtHeSoCong;
    private javax.swing.JTextField txtHeSoThamNien;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JLabel txtLuongDuocNhan;
    private javax.swing.JTextField txtLuongToiThieu;
    private javax.swing.JTextArea txtLyDoKyLuat;
    private javax.swing.JTextArea txtLyDoThuong;
    private javax.swing.JTextField txtMaCanBo;
    private javax.swing.JTextField txtMaSoCanBo2;
    private javax.swing.JTextField txtMaSoKhenThuong;
    private javax.swing.JTextField txtMaSoKyLuat;
    private javax.swing.JTextField txtMaSoThue;
    private javax.swing.JTextField txtNamThamNien;
    private javax.swing.JTextField txtNganh;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtPhuCapChucVu;
    private javax.swing.JTextField txtPhuCapNganh;
    private javax.swing.JTextField txtSoTienPhat;
    private javax.swing.JTextField txtSoTienThuong;
    // End of variables declaration//GEN-END:variables
}
