/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hungv
 */
public class itfChiBo extends javax.swing.JInternalFrame {

    DefaultTableModel dtm=new DefaultTableModel();
    /**
     * Creates new form ThongTinPhongBanView
     */
    public itfChiBo() {
        initComponents();
        creadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTimChiBo = new javax.swing.JLabel();
        txtTimChiBo = new javax.swing.JTextField();
        cbxChiBo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiBo = new javax.swing.JTable(dtm);
        btnXoaChiBo = new javax.swing.JButton();
        btnSuaChiBo = new javax.swing.JButton();
        btnThemChiBo = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1348, 555));

        lblTimChiBo.setText("TÌM KIẾM");

        cbxChiBo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MÃ CHI BỘ", "TÊN CHI BỘ" }));

        jScrollPane1.setViewportView(tblChiBo);

        btnXoaChiBo.setText("XÓA");

        btnSuaChiBo.setText("SỬA");

        btnThemChiBo.setText("THÊM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTimChiBo)
                .addGap(18, 18, 18)
                .addComponent(txtTimChiBo, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(cbxChiBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 551, Short.MAX_VALUE)
                .addComponent(btnThemChiBo)
                .addGap(34, 34, 34)
                .addComponent(btnSuaChiBo)
                .addGap(32, 32, 32)
                .addComponent(btnXoaChiBo)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimChiBo)
                    .addComponent(txtTimChiBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxChiBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaChiBo)
                    .addComponent(btnSuaChiBo)
                    .addComponent(btnThemChiBo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creadTable() {
        dtm.addColumn("MÃ CHI BỘ");
        dtm.addColumn("TÊN CHI BỘ");
        dtm.addColumn("GHI CHÚ");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaChiBo;
    private javax.swing.JButton btnThemChiBo;
    private javax.swing.JButton btnXoaChiBo;
    private javax.swing.JComboBox<String> cbxChiBo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTimChiBo;
    private javax.swing.JTable tblChiBo;
    private javax.swing.JTextField txtTimChiBo;
    // End of variables declaration//GEN-END:variables
}
