/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.QuanLyCanBo;
import Model.CanBo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hungv
 */
public class itfDanhSachCanBo extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    private QuanLyCanBo quanLyCanBo = new QuanLyCanBo();

    /**
     * Creates new form ThongTinCanBoView
     */
    public itfDanhSachCanBo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTimCanBo = new javax.swing.JLabel();
        txtTimCanBo = new javax.swing.JTextField();
        cbxTimCanBo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCanBo = new javax.swing.JTable(dtm);
        btnHienThiChiTiet = new javax.swing.JButton();
        btnXoaCanBo = new javax.swing.JButton();
        btnThemCanBo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Danh sách cán bộ");
        setPreferredSize(new java.awt.Dimension(1350, 555));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        lblTimCanBo.setText("TÌM KIẾM");

        txtTimCanBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimCanBoActionPerformed(evt);
            }
        });
        txtTimCanBo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimCanBoKeyReleased(evt);
            }
        });

        cbxTimCanBo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MÃ", "NGẠCH", "HỌ TÊN", "NGÀY SINH", "GIỚI TÍNH", "CHỨC DANH", "CHỨC VỤ", "MÃ SỐ THUẾ", "SỐ TÀI KHOẢN", "ĐỊA CHỈ", "SỐ ĐIỆN THOẠI", "EMAIL", "ĐẢNG VIÊN", "ĐOÀN VIÊN", "CÔNG ĐOÀN VIÊN", "THÀNH TÍCH", "MÃ TỔ CÔNG ĐOÀN", "MÃ CHI BỘ" }));
        cbxTimCanBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTimCanBoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tblCanBo);

        btnHienThiChiTiet.setText("HIỂN THỊ CHI TIẾT");
        btnHienThiChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiChiTietActionPerformed(evt);
            }
        });

        btnXoaCanBo.setText("XÓA");

        btnThemCanBo.setText("THÊM");

        jButton1.setText("ĐÓNG");

        jButton2.setText("SỬA");

        jButton3.setText("IN BÁO CÁO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTimCanBo)
                .addGap(18, 18, 18)
                .addComponent(txtTimCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxTimCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(btnHienThiChiTiet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThemCanBo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaCanBo)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHienThiChiTiet, btnThemCanBo, btnXoaCanBo, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimCanBo)
                    .addComponent(txtTimCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTimCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHienThiChiTiet)
                    .addComponent(btnXoaCanBo)
                    .addComponent(btnThemCanBo)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHienThiChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiChiTietActionPerformed
        // TODO add your handling code here:
        frmThongTinCanBo ttctcb = new frmThongTinCanBo();
        ttctcb.setVisible(true);
    }//GEN-LAST:event_btnHienThiChiTietActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        hienThiDuLieu("select * from thongtincanbo");
    }//GEN-LAST:event_formInternalFrameOpened

    private void cbxTimCanBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTimCanBoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTimCanBoActionPerformed

    private void txtTimCanBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimCanBoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimCanBoActionPerformed

    private void txtTimCanBoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimCanBoKeyReleased
        String kieuTimKiem = "";
        switch (cbxTimCanBo.getSelectedItem().toString()) {
            case "MÃ":
                kieuTimKiem = "MaSoCanBo";
                break;
            case "NGẠCH":
                kieuTimKiem = "Ngach";
                break;
            case "HỌ TÊN":
                kieuTimKiem = "HoTen";
                break;
            case "NGÀY SINH":
                kieuTimKiem = "NgaySinh";
                break;
            case "GIỚI TÍNH":
                kieuTimKiem = "GioiTinh";
                break;
            case "CHỨC DANH":
                kieuTimKiem = "ChucDanh";
                break;
            case "CHỨC VỤ":
                kieuTimKiem = "ChucVu";
                break;
            case "MÃ SỐ THUẾ":
                kieuTimKiem = "MaSoThue";
                break;
            case "SỐ TÀI KHOẢN":
                kieuTimKiem = "SoTaiKhoan";
                break;
            case "ĐỊA CHỈ":
                kieuTimKiem = "DiaChi";
                break;
            case "SỐ ĐIỆN THOẠI":
                kieuTimKiem = "SoDienThoai";
                break;
            case "EMAIL":
                kieuTimKiem = "Email";
                break;
            case "ĐẢNG VIÊN":
                kieuTimKiem = "DangVien";
                break;
            case "ĐOÀN VIÊN":
                kieuTimKiem = "DoanVien";
                break;
            case "CÔNG ĐOÀN VIÊN":
                kieuTimKiem = "CongDoanVien";
                break;
            case "THÀNH TÍCH":
                kieuTimKiem = "ThanhTich";
                break;
            case "MÃ TỔ CÔNG ĐOÀN":
                kieuTimKiem = "MaToCongDoan";
                break;
            case "MÃ CHI BỘ":
                kieuTimKiem = "MaChiBo";
                break;

        }
        String sql = "select * from thongtincanbo where " + kieuTimKiem
                + " like '%" + txtTimCanBo.getText() + "%';";
        this.hienThiDuLieu(sql);
    }//GEN-LAST:event_txtTimCanBoKeyReleased

    //HIỂN THỊ DANH SÁCH CÁN BỘ RA BẢNG
    public void hienThiDuLieu(String sql) {
        String[] nameColumm = {"Mã số", "Ngạch", "Họ tên", "Ngày sinh", "Giới tính",
            "Chức danh", "Chức vụ", "Mã số thuế", "Số tài khoản", "Địa chỉ",
            "Số điện thoại", "Email", "Đảng viên", "Đoàn viên", "Công đoàn viên",
            "Thành tích", "Mã chi bộ", "Mã tổ công đoàn"};
        DefaultTableModel model = new DefaultTableModel(nameColumm, 0);
        ArrayList<CanBo> lstCanBo = quanLyCanBo.getCanBo(sql);
        Object[] objCanBo = new Object[18];
        for (int i = 0; i < lstCanBo.size(); i++) {
            objCanBo[0] = lstCanBo.get(i).getMaSoCanBo();
            objCanBo[1] = lstCanBo.get(i).getNgach();
            objCanBo[2] = lstCanBo.get(i).getHoTenCanBo();
            objCanBo[3] = lstCanBo.get(i).getNgaySinh();
            objCanBo[4] = lstCanBo.get(i).getGioiTinh();
            objCanBo[5] = lstCanBo.get(i).getChucDanh();
            objCanBo[6] = lstCanBo.get(i).getChucVu();
            objCanBo[7] = lstCanBo.get(i).getMaSoThue();
            objCanBo[8] = lstCanBo.get(i).getSoTaiKhoan();
            objCanBo[9] = lstCanBo.get(i).getDiaChi();
            objCanBo[10] = lstCanBo.get(i).getSoDienThoai();
            objCanBo[11] = lstCanBo.get(i).getEmail();
            objCanBo[12] = lstCanBo.get(i).getDangVien();
            objCanBo[13] = lstCanBo.get(i).getDoanVien();
            objCanBo[14] = lstCanBo.get(i).getCongDoanVien();
            objCanBo[15] = lstCanBo.get(i).getThanhTich();
            objCanBo[16] = lstCanBo.get(i).getMaChiBo();
            objCanBo[17] = lstCanBo.get(i).getMaToCongDoan();

            model.addRow(objCanBo);
        }
        tblCanBo.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThiChiTiet;
    private javax.swing.JButton btnThemCanBo;
    private javax.swing.JButton btnXoaCanBo;
    private javax.swing.JComboBox<String> cbxTimCanBo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTimCanBo;
    private javax.swing.JTable tblCanBo;
    private javax.swing.JTextField txtTimCanBo;
    // End of variables declaration//GEN-END:variables
}
