/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hungv
 */
public class itfToCongDoan extends javax.swing.JInternalFrame {

    DefaultTableModel dtm=new DefaultTableModel();
    /**
     * Creates new form ToCongDoanView
     */
    public itfToCongDoan() {
        initComponents();
        creadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTimToCongDoan = new javax.swing.JLabel();
        txtTimToCongDoan = new javax.swing.JTextField();
        cbxToCongDoan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblToCongDoan = new javax.swing.JTable(dtm);
        btnXoaToCongDoan = new javax.swing.JButton();
        btnSuaToCongDoan = new javax.swing.JButton();
        btnThemToCongDoan = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1348, 555));

        lblTimToCongDoan.setText("TÌM KIẾM");

        cbxToCongDoan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MÃ TỔ CÔNG ĐOÀN", "TÊN TỔ CÔNG ĐOÀN" }));

        jScrollPane1.setViewportView(tblToCongDoan);

        btnXoaToCongDoan.setText("XÓA");

        btnSuaToCongDoan.setText("SỬA");

        btnThemToCongDoan.setText("THÊM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTimToCongDoan)
                .addGap(18, 18, 18)
                .addComponent(txtTimToCongDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(cbxToCongDoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 477, Short.MAX_VALUE)
                .addComponent(btnThemToCongDoan)
                .addGap(47, 47, 47)
                .addComponent(btnSuaToCongDoan)
                .addGap(41, 41, 41)
                .addComponent(btnXoaToCongDoan)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimToCongDoan)
                    .addComponent(txtTimToCongDoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxToCongDoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaToCongDoan)
                    .addComponent(btnSuaToCongDoan)
                    .addComponent(btnThemToCongDoan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creadTable() {
        dtm.addColumn("MÃ TỔ CÔNG ĐOÀN");
        dtm.addColumn("TÊN TỔ CÔNG ĐOÀN");
        dtm.addColumn("GHI CHÚ");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaToCongDoan;
    private javax.swing.JButton btnThemToCongDoan;
    private javax.swing.JButton btnXoaToCongDoan;
    private javax.swing.JComboBox<String> cbxToCongDoan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTimToCongDoan;
    private javax.swing.JTable tblToCongDoan;
    private javax.swing.JTextField txtTimToCongDoan;
    // End of variables declaration//GEN-END:variables
}
