/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hungv
 */
public class itfThongTinLuong extends javax.swing.JInternalFrame {

    DefaultTableModel dtm=new DefaultTableModel();
    /**
     * Creates new form ThongTinLuongView
     */
    public itfThongTinLuong() {
        initComponents();
        creadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTimLuong = new javax.swing.JLabel();
        txtTimLuong = new javax.swing.JTextField();
        cbxLuong = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLuong = new javax.swing.JTable(dtm);
        btnXoaLuong = new javax.swing.JButton();
        btnSuaLuong = new javax.swing.JButton();
        btnThemLuong = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1348, 555));

        lblTimLuong.setText("TÌM KIẾM");

        cbxLuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MÃ GV", "HỆ SỐ BẬC", "PHỤ CẤP CHỨC VỤ", "PHỤ CẤP NGÀNH", "NĂM THÂM NIÊN", "HỆ SỐ THÂM NIÊN", "CỘNG HỆ SỐ", "TỔNG LƯƠNG", "TỔNG TRỪ", "CÒN NHẬN" }));

        jScrollPane1.setViewportView(tblLuong);

        btnXoaLuong.setText("XÓA");

        btnSuaLuong.setText("SỬA");

        btnThemLuong.setText("THÊM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTimLuong)
                .addGap(18, 18, 18)
                .addComponent(txtTimLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(cbxLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 510, Short.MAX_VALUE)
                .addComponent(btnThemLuong)
                .addGap(42, 42, 42)
                .addComponent(btnSuaLuong)
                .addGap(34, 34, 34)
                .addComponent(btnXoaLuong)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimLuong)
                    .addComponent(txtTimLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaLuong)
                    .addComponent(btnSuaLuong)
                    .addComponent(btnThemLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creadTable() {
        dtm.addColumn("MÃ GV");
        dtm.addColumn("HỆ SỐ BẬC");
        dtm.addColumn("PHỤ CẤP CHỨC VỤ");
        dtm.addColumn("PHỤ CẤP NGÀNH");
        dtm.addColumn("NĂM THÂM NIÊN");
        dtm.addColumn("HỆ SỐ THÂM NIÊN");
        dtm.addColumn("CỘNG HỆ SỐ");
        dtm.addColumn("TỔNG LƯƠNG");
        dtm.addColumn("TỔNG TRỪ");
        dtm.addColumn("CÒN NHẬN");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaLuong;
    private javax.swing.JButton btnThemLuong;
    private javax.swing.JButton btnXoaLuong;
    private javax.swing.JComboBox<String> cbxLuong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTimLuong;
    private javax.swing.JTable tblLuong;
    private javax.swing.JTextField txtTimLuong;
    // End of variables declaration//GEN-END:variables
}
